# Theme
set-option -sa terminal-overrides  ",xterm*:TC"
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'dragon'
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-plugins "battery time git"
set -g @kanagawa-show-powerline true
set -g @kanagawa-show-left-icon session
set -g @kanagawa-show-timezone false
set -g @kanagawa-git-show-current-symbol ✓

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shift windows
bind -n C-M-h previous-window
bind -n C-M-l next-window

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Opens panes in current directory
bind _ split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

set -g mouse on

# Set Vi mode
set-window-option -g mode-keys vi
# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
